### ISSUE TITLE
博主您好！

### ISSUE THREAD

**Issue by smalpple** [laike9m/My_Blog#8]
是这样的，本人刚开始学习django框架，然后看到博主的博客想学习一下就down到本地了，然后运行mange.py
'''python
mange.py runserver
'''
结果报错
‘’‘
C:\Python34\python.exe D:/My_Blog-master/manage.py
Traceback (most recent call last):
  File "D:/My_Blog-master/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "C:\Python34\lib\site-packages\django\conf\__init__.py", line 53, in __getattr__
    self._setup(name)
  File "C:\Python34\lib\site-packages\django\conf\__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Python34\lib\site-packages\django\conf\__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "D:\My_Blog-master\my_blog\settings.py", line 3, in <module>
    from . import choose_settings
  File "D:\My_Blog-master\my_blog\choose_settings.py", line 33, in <module>
    'PASSWORD': os.environ["DJANGO_DB_PASSWORD"],
  File "C:\Python34\lib\os.py", line 635, in __getitem__
    raise KeyError(key) from None
KeyError: 'DJANGO_DB_PASSWORD'
‘’‘
不知道是因为什么。。。我的电脑是windows系统，python3.4的’

**Comment by laike9m** [comment]
这个错很明显吧……`os.environ["DJANGO_DB_PASSWORD"]` 知道含义对吧，所以你得自己设置密码才能用

**Comment by laike9m** [comment]
其实也许还有一些其它步骤比如数据库相关的初始化
