### ISSUE TITLE
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001DB1D7557

### ISSUE THREAD

**Issue by 1500256797** [laike9m/My_Blog#9]
````
E:\myblog>python manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001DB1D7557B8>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\management\commands\runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\utils\autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'mytemplatetags'
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x000001ED342667B8>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\core\management\commands\runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\utils\autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'mytemplatetags'`


出现原因：当我删掉mytemplatetags,也就是含有admin.html,base.html的那个。他就报错。
我一时也找不出错误，希望您有时间能帮帮我，不胜感激！  @@

**Comment by 1500256797** [comment]
@laike9m

**Comment by 1500256797** [comment]
@laike9m

**Comment by laike9m** [comment]
为啥要删？有什么理由么

**Comment by laike9m** [comment]
而且 mytemplatetags 里并没有你说的那几个 html 文件
https://github.com/laike9m/My_Blog/tree/master/mytemplatetags

**Comment by 1500256797** [comment]
我删了templates/admin这个文件夹。
因为它影响我安装第三方后台管理库。删掉之后，就报错了。我觉得错可能是之前作者本人自定义了后台html。

**Comment by laike9m** [comment]
其实你可以参照这个
https://github.com/laike9m/My_Blog/search?utf8=✓&q=stripleadingzero&type=
把用到 mytemplatetags 的地方全删掉，肯定就没这个问题了

**Comment by 1500256797** [comment]
mytemplatetags，我知道是用来Markdown的。  现在我不清楚除了点撤销操作还有什么措施补救？ 谢谢

**Comment by 1500256797** [comment]
好的，非常感谢！
